name: Build iOS IPA

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      # 1. Checkout repo
      - name: Checkout source
        uses: actions/checkout@v4

      # 2. Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'
          channel: stable

      # 3. Get Flutter dependencies
      - name: Flutter pub get
        run: flutter pub get

      # 4. Install compatible CocoaPods & xcodeproj
      - name: Install CocoaPods & xcodeproj
        run: |
          sudo gem uninstall cocoapods -aIx || true
          sudo gem uninstall xcodeproj -aIx || true
          sudo gem install cocoapods -v 1.15.2 --no-document
          sudo gem install xcodeproj -v 1.25.0 --no-document
          pod repo update

      # 5. Clean Pods and install
      - name: Clean and install Pods
        run: |
          cd ios
          rm -rf Pods Podfile.lock
          pod install --repo-update
          cd ..

      # 6. Build IPA (unsigned)
      - name: Build IPA
        run: flutter build ipa --no-codesign

      # 7. Upload IPA as artifact
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: build/ios/ipa/*.ipa