name: Flutter iOS Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_ios:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.29.0

      - name: Install dependencies
        run: flutter pub get

      - name: Install specific CocoaPods + xcodeproj
        run: |
          sudo gem install cocoapods -v 1.15.2
          sudo gem install xcodeproj -v 1.25.0

      - name: Clean iOS build + Pods
        run: |
          flutter clean
          rm -rf ios/Pods ios/Podfile.lock ios/Runner.xcworkspace

      - name: Rebuild iOS workspace and install Pods
        run: |
          cd ios
          pod install --repo-update
          cd ..

      - name: Build iOS app
        run: flutter build ios --no-codesign