name: Build Unsigned iOS IPA

on:
  push:
    branches:
      - main

jobs:
  build_ios_unsigned:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0' # match your local version
          channel: 'stable'

      - name: Install CocoaPods 1.16.1
        run: |
          sudo gem install cocoapods -v 1.16.1
          pod --version

      - name: Flutter pub get
        run: flutter pub get

      - name: Clean iOS build
        run: |
          flutter clean
          cd ios
          rm -rf Pods Podfile.lock
          pod install --repo-update
          cd ..

      - name: Build iOS app without codesigning
        run: flutter build ios --no-codesign

      - name: Package IPA
        run: |
          APP_NAME="modern_movie_app" # replace with your app's name
          PAYLOAD_DIR="Payload"
          mkdir -p $PAYLOAD_DIR
          cp -r build/ios/iphoneos/$APP_NAME.app $PAYLOAD_DIR/
          zip -r $APP_NAME.ipa $PAYLOAD_DIR

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-ipa
          path: modern_movie_app.ipa