name: Flutter Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android:
    name: Build Android APK & AAB
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'

      - run: flutter pub get

      - run: flutter build apk --release

      - run: flutter build appbundle --release

      - uses: actions/upload-artifact@v4
        with:
          name: android-builds
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/bundle/release/app-release.aab

  build-ios:
    name: Build iOS IPA
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'

      - name: Generate iOS build files
        run: flutter precache
        shell: bash

      - name: Flutter pub get
        run: flutter pub get
        shell: bash

      - run: flutter clean

      - name: Install iOS dependencies
        run: |
          cd ios
          rm -rf Pods Podfile.lock
          rm -rf ~/Library/Developer/Xcode/DerivedData/*
          pod install --repo-update
        shell: bash

      - run: flutter build ipa --no-codesign

      - uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: build/ios/ipa/*.ipa
