name: Flutter iOS Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-ios:
    runs-on: macos-latest
    env:
      FLUTTER_ROOT: /Users/runner/hostedtoolcache/flutter/stable
      PUB_CACHE: /Users/runner/.pub-cache
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'

      - name: Install CocoaPods + xcodeproj (compatible versions)
        run: |
          sudo gem uninstall cocoapods -aIx || true
          sudo gem uninstall xcodeproj -aIx || true
          sudo gem install cocoapods -v 1.15.2 --no-document
          sudo gem install xcodeproj -v 1.25.0 --no-document
          pod repo update

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Clean iOS Pods
        run: |
          cd ios
          rm -rf Pods Podfile.lock
          pod install --repo-update
          cd ..

      - name: Build iOS app
        run: flutter build ios --no-codesign