name: Build Unsigned iOS IPA

on:
  push:
    branches:
      - main

jobs:
  build_ios_unsigned:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'
          channel: 'stable'

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Clean iOS build
        run: flutter clean

      - name: Prepare iOS pods
        run: |
          cd ios
          pod install --repo-update
          cd ..

      - name: Build unsigned iOS app
        run: flutter build ios --no-codesign --release

      - name: Package IPA
        run: |
          IPA_PATH="build/ios/iphoneos/Runner.ipa"
          mkdir -p $(dirname $IPA_PATH)
          xcrun -sdk iphoneos PackageApplication -v build/ios/iphoneos/Runner.app -o $IPA_PATH

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-ipa
          path: build/ios/iphoneos/Runner.ipa