name: Build iOS IPA

on:
  workflow_dispatch: # run manually
  push:
    branches:
      - main

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      # 1. Checkout repo
      - name: Checkout source
        uses: actions/checkout@v4

      # 2. Install Flutter (stable channel)
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'   # match your pubspec requirements
          channel: stable

      # 3. Get Dart/Flutter deps
      - name: Flutter pub get
        run: flutter pub get

      # 4. Update CocoaPods + xcodeproj for Xcode 16
      - name: Update CocoaPods & xcodeproj
        run: |
          sudo gem install cocoapods -v 1.15.2 --no-document
          sudo gem install xcodeproj -v 1.27.0 --no-document
          pod repo update

      # 5. Clean & reinstall pods
      - name: Clean and install Pods
        run: |
          cd ios
          rm -rf Pods Podfile.lock
          pod install --repo-update
          cd ..

      # 6. Build iOS IPA (unsigned)
      - name: Build IPA
        run: flutter build ipa --no-codesign

      # 7. Upload IPA as artifact
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: build/ios/ipa/*.ipa