name: Flutter Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # manual trigger

jobs:
  build-android:
    name: Build Android APK & AAB
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0' # use your Flutter version

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Build AppBundle
        run: flutter build appbundle --release

      - name: Upload Android artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-builds
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/bundle/release/app-release.aab

  build-ios:
    runs-on: macos-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.13.5' # set your Flutter version

    - name: Install dependencies
      run: flutter pub get

    - name: Clean Flutter project
      run: flutter clean

    - name: Prepare iOS
      run: |
        cd ios
        rm -rf Pods Podfile.lock
        rm -rf ~/Library/Developer/Xcode/DerivedData/*
        pod repo update
        pod install --repo-update
      shell: bash

    - name: Build iOS IPA
      run: |
        flutter build ipa \
          --export-options-plist=ios/ExportOptions.plist \
          --no-codesign
      shell: bash

    - name: Upload IPA artifact
      uses: actions/upload-artifact@v3
      with:
        name: ios-ipa
        path: build/ios/ipa/*.ipa
