name: Flutter Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android:
    name: Build Android APK & AAB
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'

      - name: Cache Flutter Pub
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
          key: flutter-pub-${{ hashFiles('**/pubspec.yaml') }}

      - name: Get Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Build AppBundle
        run: flutter build appbundle --release

      - name: Upload Android Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-builds
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/bundle/release/app-release.aab

  build-ios:
    name: Build iOS IPA
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'

      - name: Cache Flutter Pub
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
          key: flutter-pub-${{ hashFiles('**/pubspec.yaml') }}

      - name: Get Flutter Dependencies
        run: flutter pub get

      - name: Precache iOS Artifacts
        run: flutter precache

      - name: Build iOS project (generate files)
        run: flutter build ios --no-codesign

      - name: Install CocoaPods 1.17.0+
        run: sudo gem install cocoapods -v 1.17.0

      - name: Install iOS Pods
        run: |
          cd ios
          rm -rf Pods Podfile.lock
          rm -rf ~/Library/Developer/Xcode/DerivedData/*
          pod install --repo-update

      - name: Build IPA
        run: flutter build ipa --no-codesign

      - name: Upload iOS IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: build/ios/ipa/*.ipa